cases n with nn,
exact zero_ne_succ 0,
intro h1,
have h2 := succ_inj(h1),
symmetry at h2,
rw succ_eq_add_one at h2,
have h2 := eq_zero_of_add_right_eq_self(h2),
rw one_eq_succ_zero at h2,
apply succ_ne_zero 0,
exact h2,