induction b with n hb,
rw mul_zero,
rw mul_zero,
rw add_zero,
refl,
rw mul_succ,
rw mul_succ,
rw add_succ,
rw add_succ,
rw add_comm,
rw hb,
rw <- add_assoc,
rw add_comm a, --troca lugar n com a --
refl,